language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

osx_image: xcode11.3

addons:
  apt:
    packages:
      - doxygen
      - libogg-dev
      - libopus-dev
      - libssl-dev
      - wget
  homebrew:
    brewfile: true

env: PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig

script:
  - wget https://github.com/Kitware/CMake/releases/download/v3.20.3/cmake-3.20.3-linux-x86_64.tar.gz
  - tar xzvf cmake-3.20.3-linux-x86_64.tar.gz
  - cmake-3.20.3-linux-x86_64/bin/cmake -Bbuild -H.
  - cmake-3.20.3-linux-x86_64/bin/cmake --build build
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
