name: GitHub CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    strategy:
      matrix:
        name:
          [
            ubuntu-autotools,
            ubuntu-makefile,
            macos-autotools,
            macos-makefile,
          ]
        include:

          - name: ubuntu-autotools
            os: ubuntu-latest
            build-system: autotools

          - name: ubuntu-makefile
            os: ubuntu-latest
            build-system: makefile

          - name: macos-autotools
            os: macos-latest
            build-system: autotools

          - name: macos-makefile
            os: macos-latest
            build-system: makefile

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Linux dependencies
        if: startsWith(matrix.os,'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libopus-dev libogg-dev libssl-dev
          sudo apt-get install -y doxygen

      - name: Install macOS dependencies
        if: startsWith(matrix.os,'macos')
        run: |
          brew bundle

      - name: macOS diagnostics
        if: startsWith(matrix.os,'macos')
        run: |
          which openssl
          openssl version
          echo $PKG_CONFIG_PATH
          find /usr/local -name openssl.pc
          brew link openssl
          openssl version
          pkg-config --cflags --libs openssl
          brew install openssl@1.1
          which openssl
          openssl version
          pkg-config --cflags --libs openssl

      - name: Build with Autotools
        if: startsWith(matrix.build-system,'autotools')
        run: |
          ./autogen.sh
          ./configure
          make
          make check

      - name: distcheck with Autotools
        if: startsWith(matrix.build-system,'autotools')
        run: |
          make distcheck

      - name: Build with Makefile
        if: startsWith(matrix.build-system,'makefile')
        run: |
          make -C unix
          make -C unix check

      - name: Build Documentation
        run: |
          make -C doc
